_BASE_: [
  '../datasets/iMSC_pro_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_swin_1x.yml',
  '_base_/faster_rcnn_swin_tiny_fpn.yml',
  '_base_/faster_rcnn_swin_reader.yml',
]
weights: output/faster_rcnn_swin_tiny_fpn_gn_1x/model_final

FPN:
  out_channel: 256
  norm_type: gn

BBoxHead:
  head: XConvNormHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

XConvNormHead:
  num_convs: 4
  out_channel: 1024
  norm_type: gn

epoch: 36

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [24, 33]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  clip_grad_by_norm: 1.0
  optimizer:
    type: AdamW
    weight_decay: 0.05